[package]
name = "macros"
version = "0.1.0"
authors = ["Riley Stewart <rileystewart@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.65"
quote = "1.0.9"
